language: clojure
lein: lein
script: lein do clean, check, test
jdk:
  - openjdk8
  - openjdk11
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
